name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REPOSITORY}} .

    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        
    - name: Docker push
      run: docker push ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REPOSITORY}}

    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{secrets.HOST_IP}}
        username: ${{secrets.HOST_USERNAME}}
        key: ${{secrets.HOST_KEY}}
        script: |
          sudo docker pull ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REPOSITORY}}
          sudo docker stop ${{secrets.DOCKER_REPOSITORY}}
          sudo docker rm ${{secrets.DOCKER_REPOSITORY}}
          sudo docker run --name ${{secrets.DOCKER_REPOSITORY}} -d -m 2g -p 8080:8080 ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REPOSITORY}} 
