name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Permission
      run: chmod 744 gradlew
      
    - name: Build Spring
      run: ./gradlew clean build

    - name: Build Docker image
      run: docker build -t ${{secrets.DOCKER_USERNAME}}/dundam-pick .

    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        
    - name: Docker push
      run: docker push ${{secrets.DOCKER_USERNAME}}/dundam-pick

    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{secrets.HOST_IP}}
        username: ${{secrets.HOST_USERNAME}}
        key: ${{secrets.HOST_KEY}}
        script: |
          cd /path/to/your/project
          docker-compose pull
          docker-compose down
          docker-compose up -d